### ISSUE TITLE
clarify titles with 'PBB'

### ISSUE THREAD

**Issue by goodb** [SuLab/wikidatasparqlexamples#2]
Lots of the queries say something like "all proteins added by PBB" but they don't actually look to see if the PBB bot created the items in question, they just query for things based on e.g. a 'stated in' reference pointing to UniProt of NCBI Gene.  

(I don't think its currently possible to query for the editor via the query service - you would need to integrate with the Mediawiki API to do it in program).

**Comment by stuppie** [comment]
Removed these (2 or 3) queries in question when moving over to https://www.wikidata.org/wiki/User:ProteinBoxBot/SPARQL_Examples
